language: node_js
node_js:
  - "8"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://52.160.65.103:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="localeats"
    - PORT="80"
    - MONGODB_URL="mongodb://mongodb:27017/"

script:
  - docker-compose build
  - npm test

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose up -d --remove-orphans
  on:
    branch: master