version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      NODE_ENV: production
      PORT: 80 
    networks:
       - webappnetwork
    depends_on:
        - mongodb

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
        - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
        - webappnetwork

networks:
    webappnetwork:
        driver: bridge
